# TODO: Check which parameters here are actually used and prune out all the ones that aren't

# General parameters
use_optuna: False
output_dir: '/data/datasets/research-datasets/output_dir'
seed: 906579864 
new_random: False
phase: 'val'
cfg_name: 'deit-rnt100-multistage'

# Dataset parameters
dataroot: '/data/datasets/research-datasets'
dataset: 'reid_mm/RGBNT100'
dataset_name: 'RGBNT100'
workers: 128
input_size: [224, 224] # 224 normally, 384 for larger deit
hflip: 0.5 # threshold for random horizontal flip
resize_min: 0.8 # only if data_augmentation is True
resize_max: 1.0 # only if data_augmentation is True
data_augmentation: False
augment_type: "random_erasure" # Optional: "random_erasure"
train_ratio: 0.8 # use 80% of the data for training and 20% for validation
one_hot: True
image_num_for_reid_train: 1 # Default 1 -- DO NOT CHANGE THIS ONE AND num_triplet_samples AT SAME TIME THEY DO SAME THING
image_num_for_reid_validate: 25 # Default 25
num_triplet_samples: 8 # Default 1

# Model parameters 
model_modalities: ['R', 'N', 'T']
non_generalizable_inputs: False
model_anchor_only_reid: False # false by default
model_num_cls_tokens: 1
model_num_fusion_tokens: 1
model_num_heads: 8
vit_embed_dim: 768 # 384 for dino, 768 normally
model_decoder_output_class_num: 50 # change this when changing datasets
model_fusion_combos: 'ffd'
data_token_step: 0
pretrained_model: "distilled-224"
unfreeze: True

# Loss parameters
loss_fn: "ce+triplet_euclidean_soft_margin" 
loss_weighting: 0.5
center_weighting: 0.0005
label_smoothing: 0.1
alpha: 1

# Optimizer parameters
optimizer: 'adamw'
lr: 0.000005
weight_decay: 0.001
beta1: 0.83
beta2: 0.97
lr_scheduler_name: 'warmup_sqrt_lr'
warmup_steps: 50
max_lr: 0.01
reset_scheduler: False

# Training parameters
# gpus: [5]
gpus: [4]
# gpus: [5, 6, 7, 4]

ckpt_dir: '/data/datasets/research-datasets/ckpt_dir'
ckpt_full_path: '/data/datasets/research-datasets/ckpt_dir/20230808-092335-deit-rnt100-multistage/best.pth' #'/data/datasets/research-datasets/ckpt_dir/20230807-183741-deit-rnt100-multistage/best.pth'
batch_size: 20
num_epochs: 20
print_freq: 50
model_name: "deit_gradual_fusion"
trainer_name: "trainer_rgbn_triplet"
verbose: True # print more information
max_rank: 50 # max number of ranks to calculate cmc and mAP
n_trials: 1 # number of trials for optuna

# Weights and Biases Logging
use_wandb: False
wandb_project: "mm-mafia-reid-new-mAP"
study_name: "deit-rnt100-multistage"
wandb_run_name: "deit-rnt100-multistage"
wandb_trial_name: "stage1-RN300"

hyperparams:
  lr:
    min: 0.00002
    max: 0.00002
    type: loguniform
  weight_decay:
    min: 0.001
    max: 0.001
    type: loguniform
  beta1:
    min: 0.80
    max: 0.90
    type: float
  beta2:
    min: 0.97
    max: 0.98
    type: float
  model_num_cls_tokens: 
    min: 1
    max: 1
    type: int
  model_num_fusion_tokens: 
    min: 1
    max: 1
    type: int
  model_num_heads: 
    opt: [8]
    type: categorical

# Visualization configs
visualize_embeddings: True
vis_save_path: "./visualizations/"
vis_dim: 2
vis_reduction_method: 'tsne'

